name: rem
description: "rem - read everything minder"
publish_to: 'none'
version: 1.0.0+1

environment:
  sdk: ^3.10.4

dependencies:
  flutter:
    sdk: flutter

  flutter_riverpod: ^3.0.0
  riverpod_annotation: ^4.0.0

  dio: ^5.4.0

  drift: ^2.28.0
  sqlite3_flutter_libs: ^0.6.0+eol
  path_provider: ^2.1.1
  path: ^1.8.3

  freezed_annotation: ^3.0.0
  json_annotation: ^4.8.0

  flutter_secure_storage: ^10.0.0
  shared_preferences: ^2.2.0

  go_router: ^17.1.0

  flutter_animate: ^4.3.0
  cached_network_image: ^3.3.0
  google_fonts: ^8.0.0
  cupertino_icons: ^1.0.6
  shimmer: ^3.0.0

  url_launcher: ^6.2.0
  share_plus: ^12.0.1
  connectivity_plus: ^7.0.0
  intl: ^0.20.2
  uuid: ^4.2.2
  http: ^1.1.0

  clerk_flutter: ^0.0.8-beta
  metadata_fetch: ^0.4.2
  receive_sharing_intent: ^1.8.1
  image_picker: ^1.2.1
  firebase_core: ^3.8.0
  firebase_messaging: ^15.1.5
  flutter_local_notifications: ^18.0.0
  workmanager: ^0.9.0
  timezone: ^0.10.0

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^6.0.0
  
  build_runner: ^2.4.0
  drift_dev: ^2.28.0
  freezed: ^3.0.0
  json_serializable: ^6.7.0
  riverpod_generator: ^4.0.0+1
  riverpod_lint: ^3.0.0
  
  mocktail: ^1.0.1

flutter:
  uses-material-design: true
  
  assets:
    - assets/images/
